### ISSUE TITLE
scrapy-deploy  报错 

### ISSUE THREAD

**Issue by qiao100** [clayandgithub/helloscrapy#1]
{"status": "error", "message": "Traceback (most recent call last):\\n  File \"/Users/qiaolongjin/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\\n    \"__main__\", fname, loader, pkg_name)\\n  File \"/Users/qiaolongjin/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\\n    exec code in run_globals\\n  File \"/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapyd/runner.py\", line 40, in <module>\\n    main()\\n  File \"/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapyd/runner.py\", line 37, in main\\n    execute()\\n  File \"/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapy/cmdline.py\", line 110, in execute\\n    settings = get_project_settings()\\n  File \"/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapy/utils/project.py\", line 68, in get_project_settings\\n    settings.setmodule(settings_module_path, priority='project')\\n  File \"/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapy/settings/__init__.py\", line 292, in setmodule\\n    module = import_module(module)\\n  File \"/Users/qiaolongjin/anaconda2/lib/python2.7/importlib/__init__.py\", line 37, in import_module\\n    __import__(name)\\n  File \"testbot/settings.py\", line 12, in <module>\\n    from bots import setup_django_env\\nImportError: No module named bots\\n", "node_name": "localhost"}

**Comment by MZLccc** [comment]
> {"status": "error", "message": "Traceback (most recent call last):\n File "/Users/qiaolongjin/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main\n "**main**", fname, loader, pkg_name)\n File "/Users/qiaolongjin/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code\n exec code in run_globals\n File "/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapyd/runner.py", line 40, in \n main()\n File "/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapyd/runner.py", line 37, in main\n execute()\n File "/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapy/cmdline.py", line 110, in execute\n settings = get_project_settings()\n File "/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapy/utils/project.py", line 68, in get_project_settings\n settings.setmodule(settings_module_path, priority='project')\n File "/Users/qiaolongjin/anaconda2/lib/python2.7/site-packages/scrapy/settings/**init**.py", line 292, in setmodule\n module = import_module(module)\n File "/Users/qiaolongjin/anaconda2/lib/python2.7/importlib/**init**.py", line 37, in import_module\n **import**(name)\n File "testbot/settings.py", line 12, in \n from bots import setup_django_env\nImportError: No module named bots\n", "node_name": "localhost"}

请问解决了吗我也这个问题
